### ISSUE TITLE
Feature request: remember last values

### ISSUE THREAD

**Issue by rektide** [zeropoly/commitpal#1]
If I am developing a feature over a bunch of commits, I am much more likely to pick commitpal to help me make these commits if it can remember & default to the previous values that were picked (except final message).

**Comment by danieldelcore** [comment]
Hey @rektide, that's a really good idea!

Let me check that i understand your use case. You want to remember things like "feat(MyPage):" 
So you're not having to continually pick the same thing working on larger features over multiple commits?

**Comment by rektide** [comment]
Yup, you have it! Thanks for the cool project. Cheers!

**Comment by danieldelcore** [comment]
Working on this today. I've been using CommitPal for a while now and i really want this now haha

**Comment by danieldelcore** [comment]
Done! Should be available in `1.1.0` if you're still interested 😄 
Thanks for raising this issue, really appreciate the feedback - It's a motivation boost!

**Comment by danieldelcore** [comment]
https://github.com/zeropoly/commitpal/releases/tag/v1.1.0
